---
AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 4.0

Naming/FileName:
  Enabled: false

Layout/LineLength:
  Max: 250

Metrics/AbcSize:
  Max: 100

Metrics/MethodLength:
  Max: 100

Metrics/BlockLength:
  Max: 200

Metrics/ClassLength:
  Max: 1500

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 50

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/MultilineBlockChain:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Security/CompoundHash:
  Enabled: false

...
