#!/usr/bin/env ruby
require "erb"
require "octokit"

Octokit.configure do |c|
  c.auto_paginate = true
end

Octokit::Client.new(
  access_token: ENV["GITHUB_TOKEN"]
).tap do |client|
  @repos = client.org_repos("webhippie").sort_by(&:name).reject do |row|
    [".github"].include? row.name or row.archived?
  end.map do |row|
    workflows = client.contents(row.full_name, path: '.github/workflows', query: { ref: 'master' }).map do |w|
      w.name.delete_suffix(".yml")
    end.delete_if do |r|
      ["automerge"].include? r
    end

    {
      name: row.name,
      workflows: workflows
    }
  rescue StandardError
    nil
  end.compact

  File.write(
    File.expand_path(
      "../../STATUS.md",
      __FILE__
    ),
    ERB.new(
      File.read(
        File.expand_path(
          "../../templates/status.erb",
           __FILE__
        )
      ),
      trim_mode: "-"
    ).result
  )
end
