---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: general

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  statustest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: Install tools
        uses: jdx/mise-action@v4

      - name: Install deps
        run: bundle install

      - name: Execute script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec scripts/generate-status

  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: Install tools
        uses: jdx/mise-action@v4

      - name: Terraform format
        run: terraform -chdir=terraform/ fmt -no-color -check

      - name: Terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform -chdir=terraform/ init -no-color -input=false

      - name: Terraform validate
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform -chdir=terraform/ validate -no-color

      - name: Terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform -chdir=terraform/ plan -no-color -input=false

      - name: Terraform apply
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform -chdir=terraform/ apply -no-color -input=false -auto-approve

...
